---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dev-graylog-elasticsearch
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: dev-graylog-elasticsearch
  chart:
    git: https://github.com/elastic/helm-charts.git
    ref: master
    path: elasticsearch
  values:
    esMajorVersion: 6
    image: "docker.elastic.co/elasticsearch/elasticsearch"
    imageTag: "6.8.1"
    replicas: 3
    persistence:
      enabled: false
    resources:
      requests:
        memory: 1024
    esJavaOpts: "-Xmx768m -Xms768m"
    force_deploy: 29

