apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dev-graylog-app
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: dev-graylog-app
  chart:
    git: https://github.com/helm/charts.git
    ref: master
    path: stable/graylog
  values:
    tags:
      install-mongodb: false
      install-elasticsearch: false
    graylog:
      env:
        GRAYLOG_WEB_ENABLE: 'true'
        GRAYLOG_REST_LISTEN_URI: 'http://dev-graylog-app.dev.svc.cluster.local:9000/api'
        GRAYLOG_WEB_LISTEN_URI: 'http://0.0.0.0:9000/'
        GRAYLOG_WEB_ENDPOINT_URL: 'http://graylog.kubernetes.toaster.azulinho.com/'
        GRAYLOG_FORCE_ROLLOUT: 4
      rootPassword: '!Password123456789'
      input:
        udp:
          service:
            type: NodePort
            nodePort: 30001
          ports:
            - name: gelf1
              port: 12222
      ingress:
        enabled: true
        hosts:
          - graylog.kubernetes.toaster.azulinho.com
      replicas: 1
      persistence:
        enabled: true
        storageClass: 'nfs'
        size: '1Gi'
      mongodb:
        uri: "mongodb://dev-graylog-mongodb-mongodb-replicaset-client.dev.svc.cluster.local:27017/graylog?replicaSet=rs0"
      elasticsearch:
        hosts: "http://elasticsearch-master.dev.svc.cluster.local:9200"
