apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dev-graylog-mongodb
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: dev-graylog-mongodb
  chart:
    git: https://github.com/helm/charts.git
    ref: master
    path: stable/mongodb-replicaset
  values:
    force_deploy: 25
    replicas: 1
    persistentVolume:
      enabled: false
