apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: kube-system-heapster
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: kube-system-heapster
  chart:
    git: https://github.com/helm/charts.git
    ref: master
    path: stable/heapster
